// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package gossip

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type NeighborReq struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	NodeId               string   `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	MaxNum               int32    `protobuf:"varint,3,opt,name=maxNum,proto3" json:"maxNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NeighborReq) Reset()         { *m = NeighborReq{} }
func (m *NeighborReq) String() string { return proto.CompactTextString(m) }
func (*NeighborReq) ProtoMessage()    {}
func (*NeighborReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *NeighborReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NeighborReq.Unmarshal(m, b)
}
func (m *NeighborReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NeighborReq.Marshal(b, m, deterministic)
}
func (m *NeighborReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NeighborReq.Merge(m, src)
}
func (m *NeighborReq) XXX_Size() int {
	return xxx_messageInfo_NeighborReq.Size(m)
}
func (m *NeighborReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NeighborReq.DiscardUnknown(m)
}

var xxx_messageInfo_NeighborReq proto.InternalMessageInfo

func (m *NeighborReq) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *NeighborReq) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *NeighborReq) GetMaxNum() int32 {
	if m != nil {
		return m.MaxNum
	}
	return 0
}

type NeighborRes struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	NodeId               string   `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Neighbors            []string `protobuf:"bytes,3,rep,name=neighbors,proto3" json:"neighbors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NeighborRes) Reset()         { *m = NeighborRes{} }
func (m *NeighborRes) String() string { return proto.CompactTextString(m) }
func (*NeighborRes) ProtoMessage()    {}
func (*NeighborRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *NeighborRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NeighborRes.Unmarshal(m, b)
}
func (m *NeighborRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NeighborRes.Marshal(b, m, deterministic)
}
func (m *NeighborRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NeighborRes.Merge(m, src)
}
func (m *NeighborRes) XXX_Size() int {
	return xxx_messageInfo_NeighborRes.Size(m)
}
func (m *NeighborRes) XXX_DiscardUnknown() {
	xxx_messageInfo_NeighborRes.DiscardUnknown(m)
}

var xxx_messageInfo_NeighborRes proto.InternalMessageInfo

func (m *NeighborRes) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *NeighborRes) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *NeighborRes) GetNeighbors() []string {
	if m != nil {
		return m.Neighbors
	}
	return nil
}

type GossipData struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	NodeId               string   `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Nonce                uint64   `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Payload              []byte   `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GossipData) Reset()         { *m = GossipData{} }
func (m *GossipData) String() string { return proto.CompactTextString(m) }
func (*GossipData) ProtoMessage()    {}
func (*GossipData) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *GossipData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GossipData.Unmarshal(m, b)
}
func (m *GossipData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GossipData.Marshal(b, m, deterministic)
}
func (m *GossipData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GossipData.Merge(m, src)
}
func (m *GossipData) XXX_Size() int {
	return xxx_messageInfo_GossipData.Size(m)
}
func (m *GossipData) XXX_DiscardUnknown() {
	xxx_messageInfo_GossipData.DiscardUnknown(m)
}

var xxx_messageInfo_GossipData proto.InternalMessageInfo

func (m *GossipData) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *GossipData) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *GossipData) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *GossipData) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "gossip.Empty")
	proto.RegisterType((*NeighborReq)(nil), "gossip.NeighborReq")
	proto.RegisterType((*NeighborRes)(nil), "gossip.NeighborRes")
	proto.RegisterType((*GossipData)(nil), "gossip.GossipData")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x1b, 0xd2, 0xa4, 0xcd, 0x41, 0x17, 0x53, 0x21, 0xab, 0x62, 0x88, 0x3c, 0x65, 0x0a,
	0x12, 0x48, 0x3c, 0x01, 0xa8, 0x62, 0xa9, 0x90, 0x3b, 0x31, 0xba, 0xcd, 0x29, 0x04, 0x11, 0xdb,
	0xcd, 0x19, 0x89, 0xbe, 0x3d, 0xc2, 0x4e, 0xd4, 0x0e, 0x5d, 0x32, 0x7e, 0x9f, 0xec, 0xdf, 0xbf,
	0xef, 0x60, 0xd1, 0x22, 0x91, 0xaa, 0xb1, 0xb4, 0x9d, 0x71, 0x86, 0xa5, 0xb5, 0x21, 0x6a, 0xac,
	0x98, 0x41, 0xf2, 0xda, 0x5a, 0x77, 0x14, 0x5b, 0xb8, 0xde, 0x60, 0x53, 0x7f, 0xee, 0x4c, 0x27,
	0xf1, 0xc0, 0x96, 0x90, 0x38, 0x63, 0x9b, 0x3d, 0x8f, 0xf2, 0xa8, 0xc8, 0x64, 0x00, 0x76, 0x07,
	0xa9, 0x36, 0x15, 0xbe, 0x55, 0xfc, 0xca, 0xeb, 0x9e, 0xfe, 0x7d, 0xab, 0x7e, 0x37, 0x3f, 0x2d,
	0x8f, 0xf3, 0xa8, 0x48, 0x64, 0x4f, 0xe2, 0xe3, 0x3c, 0x94, 0x46, 0x86, 0xde, 0x43, 0xa6, 0xfb,
	0xcb, 0xc4, 0xe3, 0x3c, 0x2e, 0x32, 0x79, 0x12, 0xe2, 0x0b, 0x60, 0xed, 0xbf, 0xf0, 0xa2, 0x9c,
	0x1a, 0x99, 0xbc, 0x84, 0x44, 0x1b, 0xbd, 0x47, 0xdf, 0x76, 0x2a, 0x03, 0x30, 0x0e, 0x33, 0xab,
	0x8e, 0xdf, 0x46, 0x55, 0x7c, 0x9a, 0x47, 0xc5, 0x8d, 0x1c, 0xf0, 0xf1, 0x00, 0x69, 0x78, 0x8b,
	0x3d, 0xc3, 0x7c, 0x8d, 0xee, 0x1d, 0xb1, 0x23, 0x76, 0x5b, 0x86, 0x19, 0x96, 0x67, 0x73, 0x5b,
	0x5d, 0x90, 0x24, 0x26, 0xec, 0x01, 0xe6, 0x5b, 0xd4, 0x95, 0xef, 0xca, 0x86, 0x23, 0xa7, 0xfe,
	0xab, 0xc5, 0xe0, 0xc2, 0x32, 0x26, 0xbb, 0xd4, 0xaf, 0xe9, 0xe9, 0x2f, 0x00, 0x00, 0xff, 0xff,
	0x66, 0x27, 0xf0, 0x24, 0xb7, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GossipClient is the client API for Gossip service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GossipClient interface {
	GetPeers(ctx context.Context, in *NeighborReq, opts ...grpc.CallOption) (*NeighborRes, error)
	SendData(ctx context.Context, in *GossipData, opts ...grpc.CallOption) (*Empty, error)
}

type gossipClient struct {
	cc *grpc.ClientConn
}

func NewGossipClient(cc *grpc.ClientConn) GossipClient {
	return &gossipClient{cc}
}

func (c *gossipClient) GetPeers(ctx context.Context, in *NeighborReq, opts ...grpc.CallOption) (*NeighborRes, error) {
	out := new(NeighborRes)
	err := c.cc.Invoke(ctx, "/gossip.Gossip/GetPeers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gossipClient) SendData(ctx context.Context, in *GossipData, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/gossip.Gossip/SendData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GossipServer is the server API for Gossip service.
type GossipServer interface {
	GetPeers(context.Context, *NeighborReq) (*NeighborRes, error)
	SendData(context.Context, *GossipData) (*Empty, error)
}

// UnimplementedGossipServer can be embedded to have forward compatible implementations.
type UnimplementedGossipServer struct {
}

func (*UnimplementedGossipServer) GetPeers(ctx context.Context, req *NeighborReq) (*NeighborRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPeers not implemented")
}
func (*UnimplementedGossipServer) SendData(ctx context.Context, req *GossipData) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendData not implemented")
}

func RegisterGossipServer(s *grpc.Server, srv GossipServer) {
	s.RegisterService(&_Gossip_serviceDesc, srv)
}

func _Gossip_GetPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NeighborReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipServer).GetPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gossip.Gossip/GetPeers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipServer).GetPeers(ctx, req.(*NeighborReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gossip_SendData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GossipData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipServer).SendData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gossip.Gossip/SendData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipServer).SendData(ctx, req.(*GossipData))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gossip_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gossip.Gossip",
	HandlerType: (*GossipServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPeers",
			Handler:    _Gossip_GetPeers_Handler,
		},
		{
			MethodName: "SendData",
			Handler:    _Gossip_SendData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
