// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GossipMsg struct {
	// Types that are valid to be assigned to Content:
	//	*GossipMsg_NeighborReq
	//	*GossipMsg_NeighborRes
	//	*GossipMsg_Data
	Content              isGossipMsg_Content `protobuf_oneof:"content"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GossipMsg) Reset()         { *m = GossipMsg{} }
func (m *GossipMsg) String() string { return proto.CompactTextString(m) }
func (*GossipMsg) ProtoMessage()    {}
func (*GossipMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *GossipMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GossipMsg.Unmarshal(m, b)
}
func (m *GossipMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GossipMsg.Marshal(b, m, deterministic)
}
func (m *GossipMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GossipMsg.Merge(m, src)
}
func (m *GossipMsg) XXX_Size() int {
	return xxx_messageInfo_GossipMsg.Size(m)
}
func (m *GossipMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_GossipMsg.DiscardUnknown(m)
}

var xxx_messageInfo_GossipMsg proto.InternalMessageInfo

type isGossipMsg_Content interface {
	isGossipMsg_Content()
}

type GossipMsg_NeighborReq struct {
	NeighborReq *NeighborReq `protobuf:"bytes,2,opt,name=neighborReq,proto3,oneof"`
}

type GossipMsg_NeighborRes struct {
	NeighborRes *NeighborRes `protobuf:"bytes,3,opt,name=neighborRes,proto3,oneof"`
}

type GossipMsg_Data struct {
	Data *GossipData `protobuf:"bytes,4,opt,name=data,proto3,oneof"`
}

func (*GossipMsg_NeighborReq) isGossipMsg_Content() {}

func (*GossipMsg_NeighborRes) isGossipMsg_Content() {}

func (*GossipMsg_Data) isGossipMsg_Content() {}

func (m *GossipMsg) GetContent() isGossipMsg_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *GossipMsg) GetNeighborReq() *NeighborReq {
	if x, ok := m.GetContent().(*GossipMsg_NeighborReq); ok {
		return x.NeighborReq
	}
	return nil
}

func (m *GossipMsg) GetNeighborRes() *NeighborRes {
	if x, ok := m.GetContent().(*GossipMsg_NeighborRes); ok {
		return x.NeighborRes
	}
	return nil
}

func (m *GossipMsg) GetData() *GossipData {
	if x, ok := m.GetContent().(*GossipMsg_Data); ok {
		return x.Data
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GossipMsg) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GossipMsg_NeighborReq)(nil),
		(*GossipMsg_NeighborRes)(nil),
		(*GossipMsg_Data)(nil),
	}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type NeighborReq struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	MaxNum               int32    `protobuf:"varint,2,opt,name=maxNum,proto3" json:"maxNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NeighborReq) Reset()         { *m = NeighborReq{} }
func (m *NeighborReq) String() string { return proto.CompactTextString(m) }
func (*NeighborReq) ProtoMessage()    {}
func (*NeighborReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *NeighborReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NeighborReq.Unmarshal(m, b)
}
func (m *NeighborReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NeighborReq.Marshal(b, m, deterministic)
}
func (m *NeighborReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NeighborReq.Merge(m, src)
}
func (m *NeighborReq) XXX_Size() int {
	return xxx_messageInfo_NeighborReq.Size(m)
}
func (m *NeighborReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NeighborReq.DiscardUnknown(m)
}

var xxx_messageInfo_NeighborReq proto.InternalMessageInfo

func (m *NeighborReq) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *NeighborReq) GetMaxNum() int32 {
	if m != nil {
		return m.MaxNum
	}
	return 0
}

type NeighborRes struct {
	Topic                string              `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Nodes                []*NeighborRes_Addr `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *NeighborRes) Reset()         { *m = NeighborRes{} }
func (m *NeighborRes) String() string { return proto.CompactTextString(m) }
func (*NeighborRes) ProtoMessage()    {}
func (*NeighborRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *NeighborRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NeighborRes.Unmarshal(m, b)
}
func (m *NeighborRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NeighborRes.Marshal(b, m, deterministic)
}
func (m *NeighborRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NeighborRes.Merge(m, src)
}
func (m *NeighborRes) XXX_Size() int {
	return xxx_messageInfo_NeighborRes.Size(m)
}
func (m *NeighborRes) XXX_DiscardUnknown() {
	xxx_messageInfo_NeighborRes.DiscardUnknown(m)
}

var xxx_messageInfo_NeighborRes proto.InternalMessageInfo

func (m *NeighborRes) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *NeighborRes) GetNodes() []*NeighborRes_Addr {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type NeighborRes_Addr struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NeighborRes_Addr) Reset()         { *m = NeighborRes_Addr{} }
func (m *NeighborRes_Addr) String() string { return proto.CompactTextString(m) }
func (*NeighborRes_Addr) ProtoMessage()    {}
func (*NeighborRes_Addr) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3, 0}
}

func (m *NeighborRes_Addr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NeighborRes_Addr.Unmarshal(m, b)
}
func (m *NeighborRes_Addr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NeighborRes_Addr.Marshal(b, m, deterministic)
}
func (m *NeighborRes_Addr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NeighborRes_Addr.Merge(m, src)
}
func (m *NeighborRes_Addr) XXX_Size() int {
	return xxx_messageInfo_NeighborRes_Addr.Size(m)
}
func (m *NeighborRes_Addr) XXX_DiscardUnknown() {
	xxx_messageInfo_NeighborRes_Addr.DiscardUnknown(m)
}

var xxx_messageInfo_NeighborRes_Addr proto.InternalMessageInfo

func (m *NeighborRes_Addr) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *NeighborRes_Addr) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type GossipData struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Nonce                []byte   `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Payload              []byte   `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GossipData) Reset()         { *m = GossipData{} }
func (m *GossipData) String() string { return proto.CompactTextString(m) }
func (*GossipData) ProtoMessage()    {}
func (*GossipData) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *GossipData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GossipData.Unmarshal(m, b)
}
func (m *GossipData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GossipData.Marshal(b, m, deterministic)
}
func (m *GossipData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GossipData.Merge(m, src)
}
func (m *GossipData) XXX_Size() int {
	return xxx_messageInfo_GossipData.Size(m)
}
func (m *GossipData) XXX_DiscardUnknown() {
	xxx_messageInfo_GossipData.DiscardUnknown(m)
}

var xxx_messageInfo_GossipData proto.InternalMessageInfo

func (m *GossipData) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *GossipData) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *GossipData) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*GossipMsg)(nil), "message.GossipMsg")
	proto.RegisterType((*Empty)(nil), "message.Empty")
	proto.RegisterType((*NeighborReq)(nil), "message.NeighborReq")
	proto.RegisterType((*NeighborRes)(nil), "message.NeighborRes")
	proto.RegisterType((*NeighborRes_Addr)(nil), "message.NeighborRes.Addr")
	proto.RegisterType((*GossipData)(nil), "message.GossipData")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4f, 0x4f, 0xc2, 0x30,
	0x18, 0xc6, 0xb7, 0xb1, 0x31, 0x78, 0x87, 0x1c, 0x5e, 0x89, 0x99, 0x9c, 0xc8, 0x4e, 0xe8, 0x01,
	0x23, 0x5e, 0x48, 0x3c, 0x69, 0x34, 0x70, 0x91, 0x98, 0xfa, 0x09, 0x0a, 0x6d, 0x70, 0x89, 0x6b,
	0xeb, 0x5a, 0x12, 0xb9, 0xf9, 0xa5, 0xfc, 0x7e, 0x86, 0x76, 0xfc, 0x4b, 0xc6, 0x6d, 0xcf, 0xfa,
	0xfe, 0xde, 0x3c, 0x4f, 0x9f, 0xc2, 0x45, 0xc1, 0xb5, 0xa6, 0x2b, 0x3e, 0x52, 0xa5, 0x34, 0x12,
	0xe3, 0x4a, 0x66, 0x7f, 0x3e, 0xb4, 0xa7, 0x52, 0xeb, 0x5c, 0xbd, 0xe9, 0x15, 0x4e, 0x20, 0x11,
	0x3c, 0x5f, 0x7d, 0x2e, 0x64, 0x49, 0xf8, 0x77, 0x1a, 0x0c, 0xfc, 0x61, 0x32, 0xee, 0x8d, 0x76,
	0xec, 0xfc, 0x70, 0x36, 0xf3, 0xc8, 0xf1, 0xe8, 0x29, 0xa9, 0xd3, 0xc6, 0x59, 0x52, 0x9f, 0x92,
	0x1a, 0x6f, 0x20, 0x64, 0xd4, 0xd0, 0x34, 0xb4, 0xc8, 0xe5, 0x1e, 0x71, 0xae, 0x5e, 0xa8, 0xa1,
	0x33, 0x8f, 0xd8, 0x91, 0xe7, 0x36, 0xc4, 0x4b, 0x29, 0x0c, 0x17, 0x26, 0x8b, 0x21, 0x7a, 0x2d,
	0x94, 0xd9, 0x64, 0x8f, 0x90, 0x1c, 0xd9, 0xc2, 0x1e, 0x44, 0x46, 0xaa, 0x7c, 0x99, 0xfa, 0x03,
	0x7f, 0xd8, 0x26, 0x4e, 0xe0, 0x15, 0x34, 0x0b, 0xfa, 0x33, 0x5f, 0x17, 0x36, 0x52, 0x44, 0x2a,
	0x95, 0xfd, 0xfa, 0xc7, 0xb4, 0x3e, 0x43, 0xdf, 0x41, 0x24, 0x24, 0xe3, 0x3a, 0x0d, 0x06, 0x8d,
	0x61, 0x32, 0xbe, 0xae, 0x4b, 0x35, 0x7a, 0x62, 0xac, 0x24, 0x6e, 0xae, 0x7f, 0x0b, 0xe1, 0x56,
	0x62, 0x17, 0x82, 0x5c, 0x55, 0xbb, 0x82, 0x5c, 0x21, 0x42, 0xa8, 0x64, 0x69, 0x2a, 0x13, 0xf6,
	0x3b, 0x23, 0x00, 0x87, 0xa4, 0x67, 0x0c, 0xf4, 0xb6, 0x06, 0xc4, 0x92, 0x5b, 0xb0, 0x43, 0x9c,
	0xc0, 0x14, 0x62, 0x45, 0x37, 0x5f, 0x92, 0x32, 0x7b, 0xdd, 0x1d, 0xb2, 0x93, 0xe3, 0x35, 0x34,
	0xdd, 0x4e, 0x9c, 0x40, 0x6b, 0xca, 0xcd, 0x3b, 0xe7, 0xa5, 0xc6, 0xda, 0x1e, 0xfb, 0xb5, 0x1d,
	0x65, 0x1e, 0xde, 0x43, 0xeb, 0x83, 0x0b, 0x66, 0x5d, 0xd5, 0x95, 0xd2, 0xef, 0xee, 0x7f, 0xba,
	0x22, 0xbc, 0x45, 0xd3, 0xbe, 0xad, 0x87, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd6, 0xce, 0xb0,
	0x1d, 0x6c, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GossipClient is the client API for Gossip service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GossipClient interface {
	GetPeers(ctx context.Context, in *NeighborReq, opts ...grpc.CallOption) (*NeighborRes, error)
	SendData(ctx context.Context, in *GossipData, opts ...grpc.CallOption) (*Empty, error)
}

type gossipClient struct {
	cc *grpc.ClientConn
}

func NewGossipClient(cc *grpc.ClientConn) GossipClient {
	return &gossipClient{cc}
}

func (c *gossipClient) GetPeers(ctx context.Context, in *NeighborReq, opts ...grpc.CallOption) (*NeighborRes, error) {
	out := new(NeighborRes)
	err := c.cc.Invoke(ctx, "/message.Gossip/GetPeers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gossipClient) SendData(ctx context.Context, in *GossipData, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/message.Gossip/SendData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GossipServer is the server API for Gossip service.
type GossipServer interface {
	GetPeers(context.Context, *NeighborReq) (*NeighborRes, error)
	SendData(context.Context, *GossipData) (*Empty, error)
}

// UnimplementedGossipServer can be embedded to have forward compatible implementations.
type UnimplementedGossipServer struct {
}

func (*UnimplementedGossipServer) GetPeers(ctx context.Context, req *NeighborReq) (*NeighborRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPeers not implemented")
}
func (*UnimplementedGossipServer) SendData(ctx context.Context, req *GossipData) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendData not implemented")
}

func RegisterGossipServer(s *grpc.Server, srv GossipServer) {
	s.RegisterService(&_Gossip_serviceDesc, srv)
}

func _Gossip_GetPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NeighborReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipServer).GetPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Gossip/GetPeers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipServer).GetPeers(ctx, req.(*NeighborReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gossip_SendData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GossipData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipServer).SendData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Gossip/SendData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipServer).SendData(ctx, req.(*GossipData))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gossip_serviceDesc = grpc.ServiceDesc{
	ServiceName: "message.Gossip",
	HandlerType: (*GossipServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPeers",
			Handler:    _Gossip_GetPeers_Handler,
		},
		{
			MethodName: "SendData",
			Handler:    _Gossip_SendData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
