// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GossipMsg struct {
	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	// Types that are valid to be assigned to Content:
	//	*GossipMsg_NeighborReq
	//	*GossipMsg_NeighborRes
	//	*GossipMsg_Data
	Content              isGossipMsg_Content `protobuf_oneof:"content"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GossipMsg) Reset()         { *m = GossipMsg{} }
func (m *GossipMsg) String() string { return proto.CompactTextString(m) }
func (*GossipMsg) ProtoMessage()    {}
func (*GossipMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *GossipMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GossipMsg.Unmarshal(m, b)
}
func (m *GossipMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GossipMsg.Marshal(b, m, deterministic)
}
func (m *GossipMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GossipMsg.Merge(m, src)
}
func (m *GossipMsg) XXX_Size() int {
	return xxx_messageInfo_GossipMsg.Size(m)
}
func (m *GossipMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_GossipMsg.DiscardUnknown(m)
}

var xxx_messageInfo_GossipMsg proto.InternalMessageInfo

func (m *GossipMsg) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type isGossipMsg_Content interface {
	isGossipMsg_Content()
}

type GossipMsg_NeighborReq struct {
	NeighborReq *NeighborReq `protobuf:"bytes,2,opt,name=neighborReq,proto3,oneof"`
}

type GossipMsg_NeighborRes struct {
	NeighborRes *NeighborRes `protobuf:"bytes,3,opt,name=neighborRes,proto3,oneof"`
}

type GossipMsg_Data struct {
	Data *Data `protobuf:"bytes,4,opt,name=data,proto3,oneof"`
}

func (*GossipMsg_NeighborReq) isGossipMsg_Content() {}

func (*GossipMsg_NeighborRes) isGossipMsg_Content() {}

func (*GossipMsg_Data) isGossipMsg_Content() {}

func (m *GossipMsg) GetContent() isGossipMsg_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *GossipMsg) GetNeighborReq() *NeighborReq {
	if x, ok := m.GetContent().(*GossipMsg_NeighborReq); ok {
		return x.NeighborReq
	}
	return nil
}

func (m *GossipMsg) GetNeighborRes() *NeighborRes {
	if x, ok := m.GetContent().(*GossipMsg_NeighborRes); ok {
		return x.NeighborRes
	}
	return nil
}

func (m *GossipMsg) GetData() *Data {
	if x, ok := m.GetContent().(*GossipMsg_Data); ok {
		return x.Data
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GossipMsg) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GossipMsg_NeighborReq)(nil),
		(*GossipMsg_NeighborRes)(nil),
		(*GossipMsg_Data)(nil),
	}
}

type NeighborReq struct {
	MaxNum               int32    `protobuf:"varint,1,opt,name=maxNum,proto3" json:"maxNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NeighborReq) Reset()         { *m = NeighborReq{} }
func (m *NeighborReq) String() string { return proto.CompactTextString(m) }
func (*NeighborReq) ProtoMessage()    {}
func (*NeighborReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *NeighborReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NeighborReq.Unmarshal(m, b)
}
func (m *NeighborReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NeighborReq.Marshal(b, m, deterministic)
}
func (m *NeighborReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NeighborReq.Merge(m, src)
}
func (m *NeighborReq) XXX_Size() int {
	return xxx_messageInfo_NeighborReq.Size(m)
}
func (m *NeighborReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NeighborReq.DiscardUnknown(m)
}

var xxx_messageInfo_NeighborReq proto.InternalMessageInfo

func (m *NeighborReq) GetMaxNum() int32 {
	if m != nil {
		return m.MaxNum
	}
	return 0
}

type NeighborRes struct {
	Nodes                []*NeighborRes_Addr `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *NeighborRes) Reset()         { *m = NeighborRes{} }
func (m *NeighborRes) String() string { return proto.CompactTextString(m) }
func (*NeighborRes) ProtoMessage()    {}
func (*NeighborRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *NeighborRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NeighborRes.Unmarshal(m, b)
}
func (m *NeighborRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NeighborRes.Marshal(b, m, deterministic)
}
func (m *NeighborRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NeighborRes.Merge(m, src)
}
func (m *NeighborRes) XXX_Size() int {
	return xxx_messageInfo_NeighborRes.Size(m)
}
func (m *NeighborRes) XXX_DiscardUnknown() {
	xxx_messageInfo_NeighborRes.DiscardUnknown(m)
}

var xxx_messageInfo_NeighborRes proto.InternalMessageInfo

func (m *NeighborRes) GetNodes() []*NeighborRes_Addr {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type NeighborRes_Addr struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NeighborRes_Addr) Reset()         { *m = NeighborRes_Addr{} }
func (m *NeighborRes_Addr) String() string { return proto.CompactTextString(m) }
func (*NeighborRes_Addr) ProtoMessage()    {}
func (*NeighborRes_Addr) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2, 0}
}

func (m *NeighborRes_Addr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NeighborRes_Addr.Unmarshal(m, b)
}
func (m *NeighborRes_Addr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NeighborRes_Addr.Marshal(b, m, deterministic)
}
func (m *NeighborRes_Addr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NeighborRes_Addr.Merge(m, src)
}
func (m *NeighborRes_Addr) XXX_Size() int {
	return xxx_messageInfo_NeighborRes_Addr.Size(m)
}
func (m *NeighborRes_Addr) XXX_DiscardUnknown() {
	xxx_messageInfo_NeighborRes_Addr.DiscardUnknown(m)
}

var xxx_messageInfo_NeighborRes_Addr proto.InternalMessageInfo

func (m *NeighborRes_Addr) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *NeighborRes_Addr) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type Data struct {
	Nonce                []byte   `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *Data) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*GossipMsg)(nil), "message.GossipMsg")
	proto.RegisterType((*NeighborReq)(nil), "message.NeighborReq")
	proto.RegisterType((*NeighborRes)(nil), "message.NeighborRes")
	proto.RegisterType((*NeighborRes_Addr)(nil), "message.NeighborRes.Addr")
	proto.RegisterType((*Data)(nil), "message.Data")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x51, 0x4b, 0xf3, 0x30,
	0x14, 0x86, 0xd7, 0xae, 0x5d, 0xe9, 0xe9, 0xf6, 0x5d, 0x84, 0xf1, 0x11, 0xbd, 0x2a, 0x15, 0xa1,
	0x78, 0x51, 0x61, 0x82, 0x78, 0xab, 0x08, 0xee, 0xc6, 0x5d, 0xe4, 0x1f, 0x64, 0x6d, 0xa8, 0x15,
	0x9b, 0x13, 0x7b, 0x22, 0xe8, 0x0f, 0xf4, 0x7f, 0x49, 0xd3, 0x4e, 0x3b, 0xd0, 0xbb, 0x3c, 0x9c,
	0xf7, 0x09, 0x27, 0x6f, 0x60, 0xd5, 0x2a, 0x22, 0x59, 0xab, 0xc2, 0x74, 0x68, 0x91, 0x45, 0x23,
	0x66, 0x9f, 0x1e, 0xc4, 0x0f, 0x48, 0xd4, 0x98, 0x47, 0xaa, 0xd9, 0x1a, 0x42, 0x8b, 0xa6, 0x29,
	0xb9, 0x97, 0x7a, 0x79, 0x2c, 0x06, 0x60, 0x37, 0x90, 0x68, 0xd5, 0xd4, 0x4f, 0x7b, 0xec, 0x84,
	0x7a, 0xe5, 0x7e, 0xea, 0xe5, 0xc9, 0x66, 0x5d, 0x1c, 0x6e, 0xdc, 0xfd, 0xcc, 0xb6, 0x33, 0x31,
	0x8d, 0x1e, 0x9b, 0xc4, 0xe7, 0x7f, 0x9a, 0x74, 0x6c, 0x12, 0x3b, 0x83, 0xa0, 0x92, 0x56, 0xf2,
	0xc0, 0x29, 0xab, 0x6f, 0xe5, 0x5e, 0x5a, 0xb9, 0x9d, 0x09, 0x37, 0xbc, 0x8b, 0x21, 0x2a, 0x51,
	0x5b, 0xa5, 0x6d, 0x76, 0x0e, 0xc9, 0x64, 0x0f, 0xf6, 0x1f, 0x16, 0xad, 0x7c, 0xdf, 0xbd, 0xb5,
	0xee, 0x25, 0xa1, 0x18, 0x29, 0x7b, 0x9e, 0xc6, 0x88, 0x5d, 0x42, 0xa8, 0xb1, 0x52, 0xc4, 0xbd,
	0x74, 0x9e, 0x27, 0x9b, 0x93, 0xdf, 0x36, 0x2b, 0x6e, 0xab, 0xaa, 0x13, 0x43, 0xee, 0xf4, 0x02,
	0x82, 0x1e, 0xd9, 0x3f, 0xf0, 0x1b, 0x33, 0xb6, 0xe4, 0x37, 0x86, 0x31, 0x08, 0x0c, 0x76, 0xd6,
	0x75, 0x13, 0x0a, 0x77, 0xce, 0xae, 0x21, 0xe8, 0xb7, 0xed, 0x4b, 0xd5, 0xa8, 0x4b, 0xe5, 0xe2,
	0x4b, 0x31, 0x00, 0xe3, 0x10, 0x19, 0xf9, 0xf1, 0x82, 0xb2, 0x72, 0xd2, 0x52, 0x1c, 0x70, 0xbf,
	0x70, 0x5f, 0x74, 0xf5, 0x15, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x44, 0x9c, 0x79, 0xb3, 0x01, 0x00,
	0x00,
}
